

export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const FETCH_STUDENTS_LOADING = "FETCH_STUDENTS_LOADING";
export const FETCH_STUDENTS_FAILED = "FETCH_STUDENTS_FAILED";

export const FETCH_STUDENT = "FETCH_STUDENT";
export const FETCH_STUDENT_LOADING = "FETCH_STUDENT_LOADING";
export const FETCH_STUDENT_FAILED = "FETCH_STUDENT_FAILED";
export const DELETE_STUDENT = "DELETE_STUDENT";

export const MODIFY_STUDENT_SUCCESS = "MODIFY_STUDENT_SUCCESS";
export const MODIFY_STUDENT_FAILED = "MODIFY_STUDENT_FAILED";
export const ERROR_STUDENT = "ERROR_STUDENT";


export const FETCH_STAFFS = "FETCH_STAFFS";
export const FETCH_STAFFS_LOADING = "FETCH_STAFFS_LOADING";
export const FETCH_STAFFS_FAILED = "FETCH_STAFFS_FAILED";

export const FETCH_STAFF = "FETCH_STAFF";
export const FETCH_STAFF_LOADING = "FETCH_STAFF_LOADING";
export const FETCH_STAFF_FAILED = "FETCH_STAFF_FAILED";
export const DELETE_STAFF = "DELETE_STAFF";

export const MODIFY_STAFF_SUCCESS = "MODIFY_STAFF_SUCCESS";
export const MODIFY_STAFF_FAILED = "MODIFY_STAFF_FAILED";
export const ERROR_STAFF = "ERROR_STAFF";



export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";


export const GET_ERRORS = "GET_ERRORS";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
